# Ideas {-}

***

## What's Markdown? {-}

```
Markdown is a simple formatting syntax for authorship of HTML, PDF, and MS Word 
documents. Your differential lies is the facility to read and write documents.
```

In summary, Markdown is:

***

1. A simple text formatting syntax;
2. A software tool, written in Perl^[**Perl** is an programming language very used
                                     in UNIX systems administratives tasks, web
                                     development, finances, www form programming
                                     and bioinformatic, also having very efficient
                                     functions for text manipulation.], that
   converts simples text formatting in HTML.

***

> **Typing "online markdown editor" in [Google](http://www.google.com) you can
    found several different websites that allow you, online, to create, edit,
    compile and save our Markdown file in different extentions (HTML, pdf) and 
    making connections with Dropbox, GitHub, etc.**

## What's R Markdown? {-}

```
R Markdown is a markdown that recognize R code.

Inside a rmd file you can insert R code.
```

## And where I do this? {-}

A Markdown file has the extention .md, and can be created and edited in any
programming language editor. The same with R Markdown (.rmd extention), **if** you
are able to run R in this editor.

You can use the "pure" R, without any editor. You can use
[Emacs](https://www.gnu.org/software/emacs/), [Vim](https://vim.sourceforge.io/),
[Sublime](https://www.sublimetext.com/), etc.

But, for rmd files the most friendly interface is
[RStudio](https://www.rstudio.com/).